for review
PalomoBravas/jsAdvanced pull request #2
Opened 2023-06-19 14:14 UTC by PalomoBravas

2023-06-21 08:39 UTC, Grinv requested changes

2023-06-21 08:39 UTC, Grinv commented on 4-timer/script.js
> +const deadline = new Date('2023-07-26')
По заданию там немножко другое. Нужно показывать время до конца текущего года.
Т.е. нам нужно понять, что сейчас за год, создать дату конца текущего года и запустить таймер.

Если хотел немного модифицировать или усложнить или сделать, что более интересно - то ок, принимаю :)

2023-06-21 08:39 UTC, Grinv commented on 4-timer/script.js
> +  return {date, time}
А зачем такое усложие и оверкилл?
Есть же прекрасный new Date() с методами getDate, getMonth и т.д. Они надёжнее вычислят все эти параметры и не придётся парсить строку

2023-06-21 08:39 UTC, Grinv commented on 4-timer/script.js
> +  switch (true) {
Ох лучше не используй такую конструкцию, она плохо читается. В таком случае можно сделать отдельную функцию `pluralizeSeconds`
```javascript
function pluralizeSeconds(left) {
   if (left.sec < 5 && left.sec > 1) {
      return 'секунды';
   }

   if (left.sec === 1) {
      return 'секунда';
   }

   return 'секунд';
}
```
Так более изящно и читабельно получается

2023-06-21 08:39 UTC, Grinv commented on 4-timer/script.js
> +  return `${left.months} месяцев ${left.days} дней ${left.hour} часов ${left.min} минут ${left.sec} ${seconds}`
Склонение секунд сделал, но забыл про месяцы, дни, часы и минуты :)
'день, дня, дней'
'час, часа, часов'
и т.д.

2023-06-21 08:39 UTC, Grinv commented on 4-timer/script.js
> +}
Хорошей практикой считается делать максимально универсальные функции.
В данном случае она у тебя чисто заточена под секунды, но тебе нужно через неё прогнать и минуты и секунды и т.д. Поэтому я бы посоветовал передавать 2 параметра: количество и массив с 3 вариантами склонения слова и функция возвращала бы правильный вариант.
```javascript
pluralize(1, ['месяц', 'месяца', 'месяцев'])

2023-06-21 08:39 UTC, Grinv commented on 4-timer/script.js
> +}
Для функции выбора правильного склонения уже есть устоявшийся термин plural ну или pluralize

Ну и к тому же уже есть нативный метод для её реализации в `Intl.PluralRules`
Как такое написать может помочь например эта статья https://2ality.com/2019/12/intl-pluralrules.html
Советую прочитать и попытаться реализовать :)

2023-06-21 08:39 UTC, Grinv commented on 4-timer/script.js
> +  }
Впринципе тут тоже оверкилл. Можно из одной даты вычитать другую и ты узнаешь разницу между датами в миллисекундах
```javascript
const datesDiff = new Date("8/11/2023") - new Date("7/11/2022");
```
из этого уже можно будет спокойно сформировать свои данные, например
```javascript
const DAY_IN_MILLISECONDS = 1000 * 60 * 60 * 24
const daysDiff = Math.ceil(datesDiff / DAY_IN_MILLISECONDS);

2023-06-21 08:39 UTC, Grinv commented on 4-timer/script.js
> +  const [deadlineYear, deadlineMonth] = formatDateToArr(deadline).date
Данные по дэдлайну нужно посчитать только лишь один раз, когда мы запускаем функцию, ибо дедлайн не меняется и данные по нему остаются актуальные. А тут получается, что каждый раз при запуске функции мы делаем этот лишний перерасчёт. Лучше посчитать и сохранить это вне вызова интервала.

2023-06-21 08:39 UTC, Grinv commented on 4-timer/script.js
> +function timer() {
Функции лучше называть, начиная с глагола, `do...`, `get...`, `set...`, `activate...`
Тут для самодокументирования и понимая, что функция делает, не заглядывая в неё, можно назвать например `getTimerText`. Просто, лаконично и сразу понятно

2023-06-21 08:39 UTC, Grinv commented on 5-oop/script.js
> +// Orc.prototype.constructor = Orc;
Не забываем убирать лишний код и комментарии

2023-06-21 08:39 UTC, Grinv commented on 5-oop/script.js
> +// Elf.prototype.constructor = Elf
Тоже лишний комментарий

2023-06-21 08:39 UTC, Grinv commented on 5-oop/script.js
> +elf1.wiz();
Молодец! Хорошая работа👍

2023-06-21 08:39 UTC, Grinv commented on 6-class/script.js
> +  }
геттеры и сеттеры называем без get и set :)

```javascript
class Car {
   get mileage() {
      console.log(this.#mileage);
   }

   set mileage(mileage) {
      this.#mileage = mileage;
   }
}

2023-06-21 08:39 UTC, Grinv commented on 6-class/script.js
> +car1.info();
Молодец👍

2023-06-21 08:39 UTC, Grinv commented on 6-class/script.js
> +    console.log(this.#mileage);
Это сайд-эффект, который в геттере не должен быть.
Геттер должен именно возвращать что-то.
```javascript
get mileage() {
   return this.#mileage;
}

2023-06-21 08:39 UTC, Grinv commented on 6-class/script.js
> +    console.log(`This ${this.#brand} ${this.#model} with mileage ${this.#mileage}`);
Хорошо бы здесь воспользовать вышенаписанным геттером
```javascript
console.log(`...with mileage ${this.mileage}`);

2023-06-22 08:13 UTC, PalomoBravas commented on 4-timer/script.js
> +  return {date, time}
Попробовал, но не очень понравилось, нужно следить за правильным месяцем, подставлять нули если числа однозначные. Через парсинг строки получается компактнее на мой взгляд, но если это критично - исправлю

2023-06-22 09:28 UTC, PalomoBravas commented on 4-timer/script.js
> +  return `${left.months} месяцев ${left.days} дней ${left.hour} часов ${left.min} минут ${left.sec} ${seconds}`
Перешел на английский что бы не писать отдельно функцию множественног числа числительных (40минут или 39 минут/ы)

2023-06-22 13:24 UTC, PalomoBravas commented on 4-timer/script.js
> +  }
Да я так пошел изначально, но потом понял, что получив количество дней я не получу правильно количество месяцев с учетом високосных годов и разного количества дней в месяце. И по этой же причине я парсю дату, что бы не получить головную боль с количеством дней в месяце.

2023-06-29 15:58 UTC, Grinv requested changes

2023-06-29 15:58 UTC, Grinv commented on 4-timer/script.js
> +      default:
Лучше не описывать 'many', как дефолтное поведение, потому что оно таковым не является, пропиши его явно пожалуйста.
В дефолт у тебя по логике вообще не должно зайти и ты при заходе в default должен либо выкидывать ошибку, либо null, либо пустую строку, зависит от договорённостей

2023-06-29 15:58 UTC, Grinv commented on 4-timer/script.js
> +if (new Date('2024-01-01') - Date.now() === 0) {
Как я раньше и написал, не задай явную дату, вычисляй относительно текущего года.
Если я через полгода запущу твой скрипт, он же не будет работать, мне придётся править дату.

2023-06-29 15:58 UTC, Grinv commented on 4-timer/script.js
> +  }
Так и не исправил. Тебе не нужна эта логика, просто вычти из одной даты другую и ты получишь разницу в миллисекундах. Из неё спокойно можно вытянуть количество секунд, дней, месяцев и т.д.
Посмотри пожалуйста ещё раз вот этот комментарий
https://github.com/PalomoBravas/jsAdvanced/pull/2/files#r1236606793

2023-06-29 15:58 UTC, Grinv commented on 4-timer/script.js
> +function getTimerText(obj) {
Я ж ниже описал интерфейс) Сделай пожалуйста функцию универсальной. Нужно принимать 3 варианта и количество. Если она в другом месте пригодится, при такой реализации ты не сможешь её применить. Ну и название тоже нужно поменять. Всё написал в комментарии https://github.com/PalomoBravas/jsAdvanced/pull/2/files#r1236583910.

2023-06-29 15:58 UTC, Grinv commented on 4-timer/script.js
> +  timerBody.innerText = timer()
Название функции должно начинаться с глагола. runTimer, initTimer

Кстати в данном случае функция как раз и должна называться getTimerText. Что ты вставляешь в html? Правильно, текст таймера) Вот так и опиши.

2023-06-29 15:58 UTC, Grinv commented on 4-timer/script.js
> +if (new Date('2024-01-01') - Date.now() === 0) {
А если мы запускаем после 2024-01-01? Будет отрицательное число и таймер продолжит работу

2023-06-29 15:58 UTC, Grinv commented on 6-class/script.js
> +car1.info();
Да, супер.

2023-06-29 16:00 UTC, Grinv commented
Нажимай пожалуйста Resolve conversation на комментарии, который исправил, потому что сейчас начнётся путаница, где старые, а где новые, что исправленно, а что нет.
Хорошая привычка. Идёшь по код ревью. Нашёл комментарий - исправил - нажал Resolve conversation - пошёл дальше по ревью)

2023-07-02 12:54 UTC, Grinv requested changes

2023-07-02 12:54 UTC, Grinv commented on 4-timer/script.js
> +
Хм. Да, ты прав. Если б не было месяцев, то сработало бы)

Тогда давай вернёмся к твоей прошлой функции и немного отредактируем её.
1. Не надо каждый раз вызывать `new Date()`, давай один раз её объявим в переменную и будет использовать уже дальше.
2. С днями есть метод `getDate()` и небольшая хитрость с 0. Если задать вместо месяца 0, то `newDate()` отдаст последний день предыдущего месяца.

В итоге получится примерно так.
```javascript
const dateNow = new Date();
const currentMonthDaysAmount = new Date(dateNow.getFullYear(), dateNow.getMonth() + 1, 0 ).getDate();

const daysDiff = currentMonthDaysAmount - (dateNow.getDate() + 1);
```
тогда давай почистим немного код, воспользуемся этим методом. Код станет читать полегче. И не забудь удалить все переменные, которые больше не используются :)

2023-07-03 19:00 UTC, Grinv requested changes

2023-07-03 19:00 UTC, Grinv commented on 4-timer/script.js
> +  return result.join(' ')
Так, я что-то в прошлый раз пропустил, а зачем ты собираешь всё в массив и потом делаешь join? У тебя же один единственный вариант исхода, а не несколько. Сразу бы и возвращал результат.

```javascript
function pluralizeText(count, arr) {
    const grammaticalNumber = pluralRules.select(Number(count));
    switch (grammaticalNumber) {
      case 'one':
        return `${count} ${arr[2]}`;
      case 'few':
        return `${count} ${arr[1]}`;
      case 'many':
        return `${count} ${arr[0]}`;
      default:
        throw new Error('Error in pluralizeTimerText');
    }
}
```
Кажется, так выглядет гораздо проще и лучше читается.

2023-07-06 14:23 UTC, Grinv approved these changes

2023-07-06 14:23 UTC, Grinv commented on 4-timer/script.js
> +        throw new Error('Error in pluralizeTimerText');
Да, всё правильно, молодец

2023-07-06 14:23 UTC, merged