5 review
PalomoBravas/jsAdvanced pull request #5
Opened 2023-07-06 06:51 UTC by PalomoBravas

2023-07-06 15:16 UTC, Grinv requested changes

2023-07-06 15:16 UTC, Grinv commented on 14-user-task/package.json
> +}
C этими заданиями всё отлично, но забыл сделать/добавить задание из раздела "Продвинутый DOM и Events"

2023-07-07 08:55 UTC, PalomoBravas commented
Забыл добавить)

2023-07-08 16:56 UTC, Grinv requested changes

2023-07-08 16:56 UTC, Grinv commented on 13-buttons/style.css
> +button {
Глобальные стили к тэгам надо оооочень осторожно применять. Нормально применять например css-reset всякие. А если будут кнопки, к которым не хочешь применить данный стиль? Лучше либо задай класс всем кнопкам и примени его. Либо на худой конец хотя бы сузь селектор до `.button__wrapper > button`, так меньше шансов напороться на сайд-эффекты.

2023-07-08 16:56 UTC, Grinv commented on 13-buttons/script.js
> +let countNumber = 0
У каждой кнопки должен быть свой собственный счётчик нажатий. Подумай, где его можно хранить)

2023-07-08 16:56 UTC, Grinv commented on 13-buttons/script.js
> +    button.className = 'pressed'
А если мы где-нибудь в другой месте добавим этим кнопкам класс, мы ж так перезатрём его.
Если у нас есть безопасные способы что-то сделать, лучше использовать их.
Выше использовал classList, мы можем воспользоваться им и тут (`classList.add`) 😁

2023-07-08 16:56 UTC, Grinv commented on 13-buttons/script.js
> +    button.innerHTML = 'PRESSED'
А остальные кнопки нужно отжать, забыл :)

2023-07-08 16:56 UTC, Grinv commented on 13-buttons/index.html
> +  <div class="counter">23</div>
Можно воспользоваться тэгом `output`, например

2023-07-08 16:56 UTC, Grinv commented on 13-buttons/style.css
> +    text-transform: uppercase;
Ты их уже в uppercase написал)
Можешь тогда в тексте поправить на "Press me"

2023-07-13 18:53 UTC, Grinv requested changes

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +function run(numberOfButtons) {
`buttonsAmount`

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +  buttonsStateInit(numberOfButtons)
`initButtonsState`

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +  buttonsBlock.addEventListener('click', (e) => pressButton(e))
```javascript
buttonsBlock.addEventListener('click', onPressButton);

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +      if(button.toggle === true) {
Почему? А если я 2 раза хочу на одну кнопку нажать? Не сработает же)

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +    buttonsState.push({id: i, numberOfClicks: 0, toggle: false,})
Что значит в данном контексте toggle? toggle - это глагол переключения в противоположное состояние.
 Что означает флаг toggle? Вообще не понятно.
isClicked/isPressed - понятно.

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +  buttonsBlock.innerHTML = ''
Жёстко. Очень дорогими операциями занимаемся. А смысл какой? Попробовать своё ООП сделать?

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +    buttonsBlock.append(button)
Плохая практика добавлять элемент на каждую итерацию. Каждую итерацию движку приходится всё пересчитывать и перерендеривать. Лучше накопи это в один массив и одной операцией всё вставь.

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +      button.classList.remove('unpressed')
Да зачем `unpressed`?)
Сделай один общий класс какой-нибудь `btn`, а на нажатую кнопку будет вешать `pressed` и всё, тогда можно будет оперировать всего одним классом `pressed`.

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +      button.classList.remove('unpressed')
Так нам принципе удалять то и нечего. Сделали элемент 3 строчки назад только.

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +      button.classList.remove('pressed')
Тоже самое. Удалять тут точно нечего. И добавлять тож, если мы избавляемся от unpressed. В итоге вообще это условие уходит. В итоге у нас получится что-то типа:
```javascript
function createButton(state) {
   const button = document.createElement("button")
   button.classList.add('button');
   button.id = buttonState.id;
   const buttonText = buttonState.isPressed ? 'Pressed' : 'Press Me';
   button.innerHTML = `${buttonText}<br />${buttonState.numberOfClicks}`;

   if (buttonState.isPressed) {
      button.classList.add('pressed')
   }

   return button;
}
```
выглядит получше.

Ну и как второй вариант, можно всё это писать в JSX стиле. Мне он нравится больше, потому что читабельнее. Когда мы  будем вставлять в дом дерево. движок строку правильно распарсить и вставит как обычную ноду:
```javascript
function createButton(buttonState) {
   const className = state.isPressed ? 'pressed' : '';
   const buttonText = buttonState.isPressed ? 'Pressed' : 'Press Me';
   button.innerHTML = `${buttonText}<br />${buttonState.numberOfClicks}`;

   return `
      <button id="${buttonState.id}" class="${className}">
         ${buttonText}<br />${buttonState.numberOfClicks}
      </button>`;
}

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +    button.id = buttonState.id.toString()
Зачем туда-сюда из string в number гонять? Можно ж просто id в string хранить и всё)

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +    const button = document.createElement("button")
Я бы впринципе сделал отдельный метод, который бы мне возвращал созданную кнопку. Гораздо читабельнее будет.

```javascript
for (const buttonState of buttonsState) {
    const button = createButton(buttonState);
   // ..
}

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +      button.toggle = false
Кажется это можно  превратить в одно условие 
```javascript
button.toggle = button.id === clickedButtonId;

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +counter.innerHTML = countState.count
Я бы `counter.innerHTML = countState.count` закинул в `run()`;
Да и вообще сделал бы отдельную функцию
```javascript
const countState = {count: 0};

function updateCommonCounter() {
   counter.innerHTML = countState.count;
}

function run() {
   updateCommonCounter();
}

2023-07-13 18:53 UTC, Grinv commented on 13-buttons/script.js
> +      button.toggle = true
Опять же, учитывая, что у нас может быть нажата только одна кнока, нет смысла хранить состояние нажатия в каждой кнопке, достаточно хранит только текущую нажатую кнопку.
```javascript
function pressButton(e) {
   state.pressedButtonId = e.target.id;
   // ...
}

2023-07-18 10:32 UTC, Grinv requested changes

2023-07-18 10:32 UTC, Grinv commented on 13-buttons/script.js
> +    return;
Зачем? Разве по условию я не имею права нажать два раза подряд?)

2023-07-18 10:32 UTC, Grinv commented on 13-buttons/script.js
> +  state.buttonsState[e.target.id-1].count ++;
В `initButtonsState` можно начать счётчик с 0, тогда тут не придётся отнимать единицу.

2023-07-18 10:32 UTC, Grinv commented on 13-buttons/script.js
> +function buttonsAmount(numberOfButtons) {
Нене, я про название переменной))
Лучше избавляться от предлогов, если это возможно.
А функцию лучше называть глаголом, как раньше и говорил. Например
```javascript
function initButtons(buttonsAmount) {
   // ...
}

2023-07-18 10:32 UTC, Grinv commented on 13-buttons/script.js
> +  buttonsBlock.innerHTML =  btnArr.join("\n")
Можно сильно проще сделать)
```javascript
function renderButtons() {
  const pressedButtonId = state.pressedButtonId;
  const buttons = state.buttonsState
   .map(buttonState => createButton(pressedButtonId, buttonState))
   .join("");

  buttonsBlock.innerHTML = buttons;
}

2023-07-18 10:32 UTC, Grinv commented on 13-buttons/script.js
> +  const className = pressedButtonId === buttonsState.id ? 'pressed' : '';
А зачем тебе `pressedButtonId`? Ты его используешь только для того, чтоб понять, нажата она или нет. Давай просто передавать флаг `isPressed` в эту функцию и не надо будет сравнивать и переменная не понадобится
```javascript
function createButton(isPressed, buttonsState) {
  const className = isPressed ? 'pressed' : '';

2023-07-18 10:32 UTC, Grinv commented on 13-buttons/script.js
> +}
```javascript
function buttonsAmount(numberOfButtons) {
  initButtonsState(numberOfButtons);
  rerender();
  buttonsBlock.addEventListener('click', onPressButton);
}
```
И я бы переименовал `rerender` в `updateLayout`

2023-07-18 10:32 UTC, Grinv commented on 13-buttons/style.css
> +.button {
Подумай, как можно сделать, чтоб ширина кнопок не изменялась, когда кликаем.
Дёрганье некрасиво выглядит)

2023-07-20 05:24 UTC, Grinv approved these changes

2023-07-20 05:24 UTC, Grinv commented on 13-buttons/script.js
> +  buttonsBlock.addEventListener('click', onPressButton);
Не ошибка, но как улучшение. Можно переиспользовать updateLayout, как выше писал.
```javascript
function initButtons(buttonsAmount) {
  initButtonsState(buttonsAmount);
  updateLayout();
  buttonsBlock.addEventListener('click', onPressButton);
}

2023-07-20 05:24 UTC, Grinv commented on 13-buttons/script.js
> +initButtons(5);
Супер, вот теперь всё нравится. Рекомендую сравнить начальную версию и эту и понять, насколько стало проще читать код :)

2023-07-20 05:24 UTC, merged